(function(){
'use strict';
const roots=[
['nov','新的',['novel 新颖的','innovate 创新','renovate 翻新','novelty 新奇']],['spect','看',['inspect 检查','respect 尊重','prospect 前景','perspective 视角']],['ject','投、掷',['reject 拒绝','project 项目','subject 主题','objective 客观的']],['tract','拉、引',['attract 吸引','extract 提取','contract 合同','distract 分心']],['port','携带、运送',['transport 运输','export 出口','support 支持','portable 便携的']],['scrib/script','写',['describe 描述','prescribe 开处方','manuscript 手稿','transcript 文字记录']],['struct','建造',['construct 建造','structure 结构','instruct 指导','destruction 破坏']],['form','形状、形成',['reform 改革','transform 转变','conform 遵从','formation 形成']],['press','压',['pressure 压力','express 表达','suppress 抑制','impression 印象']],['cede/ceed','走、前进',['precede 先于','proceed 继续','exceed 超过','recede 后退']],['mit/miss','送、放',['submit 提交','permit 允许','transmit 传播','mission 任务']],['dict','说、断言',['predict 预测','contradict 反驳','dictate 口授','verdict 裁决']],['bio','生命',['biology 生物学','biography 传记','biodiversity 生物多样性','antibiotic 抗生素']],['geo','地球、土地',['geography 地理','geology 地质','geopolitical 地缘政治']],['psych','心理、精神',['psychology 心理学','psychological 心理的','psychiatry 精神病学']],['chron','时间',['chronology 年表','chronic 慢性的','synchronize 同步']],['bene','好',['benefit 益处','benevolent 仁慈的','beneficial 有益的']],['mal','坏、恶',['malfunction 故障','malnutrition 营养不良','malpractice 渎职']],['inter','在……之间',['interaction 互动','international 国际的','interfere 干涉']],['trans','跨越、转变',['translate 翻译','transfer 转移','transition 过渡']],['sub','在下、次一级',['subway 地铁','subordinate 下级的','subconscious 潜意识']],['pre','在前、预先',['preview 预览','prevent 防止','preliminary 初步的']],['re','再次、向后',['review 复习','rebuild 重建','recover 恢复']],['anti','反对、抵抗',['antibiotic 抗生素','antisocial 反社会的','antidiscrimination 反歧视']]
];
const topicGroups=[
{name:'文化交流',items:[['Embrace cultural diversity.','拥抱文化多样性。'],['Preserve historical heritage.','保护历史遗产。'],['Foster cross-cultural understanding.','促进跨文化理解。'],['Enhance cultural awareness.','提高文化意识。']]},
{name:'教育与学术',items:[['Conduct a workshop on critical thinking.','举办批判性思维工作坊。'],['Achieve academic excellence through hard work.','通过努力实现学业卓越。'],['Collect and analyze data for a study.','为研究收集并分析数据。'],['Review literature on climate change.','回顾气候变化相关文献。']]},
{name:'志愿服务',items:[['Collaborate with nonprofit organizations.','与非营利组织合作。'],['Fulfill social responsibilities through service.','通过服务履行社会责任。'],['Enhance public welfare initiatives.','加强公共福利行动。'],['Make a positive impact through volunteer work.','通过志愿工作产生积极影响。']]},
{name:'健康生活',items:[['Maintain physical fitness through regular exercise.','通过规律锻炼保持身体健康。'],['Develop a healthy lifestyle to prevent chronic diseases.','养成健康生活方式以预防慢性病。'],['Manage stress through mindfulness.','通过正念管理压力。'],['Prioritize mental health.','优先关注心理健康。']]},
{name:'环境保护',items:[['Protect ecosystems by reducing pollution.','通过减少污染保护生态系统。'],['Minimize our carbon footprint.','尽量减少我们的碳足迹。'],['Support renewable energy initiatives.','支持可再生能源行动。'],['Raise awareness of biodiversity loss.','提高对生物多样性丧失的认识。']]},
{name:'职业发展',items:[['Enhance job-market competitiveness with new skills.','用新技能提高就业竞争力。'],['Pursue professional development opportunities.','寻求职业发展机会。'],['Seek mentorship to guide career decisions.','寻求导师帮助指导职业决策。'],['Tailor a résumé to highlight relevant experience.','调整简历以突出相关经历。']]},
{name:'科技创新',items:[['Embrace technological advances in the workplace.','在工作场所拥抱技术进步。'],['Drive innovation through research and development.','通过研发推动创新。'],['Adapt to digital transformation.','适应数字化转型。'],['Ensure that cybersecurity measures are in place.','确保网络安全措施落实到位。']]}
];
const translations=[
{en:'The assumption that technological progress automatically improves everyone’s life ignores the uneven way in which its benefits and costs are distributed.',main:'The assumption ignores the uneven way.',chunks:'主语：The assumption；同位语从句：that technological progress...；宾语：the uneven way；定语从句：in which...',zh:'认为技术进步会自动改善每个人生活的这一假设，忽视了其收益和成本分配不均的现实。',tip:'先译主干“这一假设忽视了……”，再把 that 从句放回“假设”的内容。'},
{en:'What matters is not whether a new policy sounds attractive, but whether it can produce measurable improvements for the people it is intended to serve.',main:'What matters is not A, but B.',chunks:'What 引导主语从句；not whether A, but whether B 为表语并列；it is intended to serve 修饰 people。',zh:'重要的不是一项新政策听起来是否有吸引力，而是它能否为其服务对象带来可衡量的改善。',tip:'not A but B 译成“不是……而是……”，两个 whether 保持并列。'},
{en:'Although access to information has expanded rapidly, the ability to judge its reliability has not developed at the same pace.',main:'The ability has not developed at the same pace.',chunks:'Although 引导让步状语从句；to judge its reliability 修饰 ability。',zh:'尽管获取信息的渠道迅速扩大，但人们判断信息可靠性的能力并未以同样的速度发展。',tip:'access 不要机械译成“接近”，此处是“获取信息的渠道/机会”。'},
{en:'People who regard failure as evidence of personal inadequacy may overlook the valuable feedback that unsuccessful attempts can provide.',main:'People may overlook the valuable feedback.',chunks:'who... 修饰 People；that... 修饰 feedback。',zh:'把失败视为个人能力不足证据的人，可能会忽略失败尝试所能提供的宝贵反馈。',tip:'先找 People may overlook，再处理前后两个定语从句。'},
{en:'The more choices consumers are offered, the more difficult it may become for them to decide which option best meets their needs.',main:'The more A, the more B.',chunks:'比较级相关结构；which option... 是 decide 的宾语从句。',zh:'消费者面对的选择越多，他们就越难判断哪个选项最符合自身需要。',tip:'the more..., the more... 固定译为“越……，就越……”。'},
{en:'By encouraging students to explain how they reached an answer, teachers can identify misunderstandings that a correct result alone might conceal.',main:'Teachers can identify misunderstandings.',chunks:'By... 作方式状语；how... 是 explain 的宾语从句；that... 修饰 misunderstandings。',zh:'通过鼓励学生解释自己如何得出答案，教师能够发现那些可能被一个正确结果掩盖的误解。',tip:'先译主句，再前置 By 短语，最后补定语从句。'},
{en:'A society’s willingness to invest in preventive care reflects not only its economic priorities but also its understanding of long-term public welfare.',main:'A society’s willingness reflects A and B.',chunks:'to invest... 修饰 willingness；not only...but also... 连接两个宾语。',zh:'一个社会是否愿意投资预防性医疗，不仅反映其经济优先事项，也反映其对长期公共福祉的理解。',tip:'抽象名词 willingness 可转译成“是否愿意”。'},
{en:'It is only when familiar routines are interrupted that people become fully aware of how strongly those routines shape their daily decisions.',main:'People become aware of...',chunks:'It is...that... 强调句；when... 是被强调的时间状语；how strongly... 是介词 of 的宾语。',zh:'只有当熟悉的日常惯例被打断时，人们才会充分意识到这些惯例在多大程度上塑造着自己的日常决定。',tip:'识别强调句后译成“只有……才……”，不要逐词硬译。'}
];
let special='roots',medicalPages=null,topicPages=null,pageIndex=0;
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function hero(title,text){return `<div class="special-hero"><h3>${title}</h3><p>${text}</p><div class="layer-badges"><span>第一轮：认懂</span><span>第二轮：会用</span><span>第三轮：会考</span></div></div>`}
function renderRoots(q=''){const list=roots.filter(x=>!q||x.join(' ').toLowerCase().includes(q.toLowerCase()));return hero('词根词缀家族记忆','不要把词根当成新的单词表死背。先抓住核心方向，再观察前缀、词根和后缀怎样共同改变词义。')+`<input id="specialSearch" class="study-filter" placeholder="搜索词根或例词" value="${esc(q)}"><div class="study-actions"><a class="primary" href="./resources/root-affix-map.pdf" target="_blank">打开完整55页思维导图</a></div><div class="root-grid">${list.map(x=>`<section class="study-card"><h4><span class="morpheme">${x[0]}</span> = ${x[1]}</h4>${x[2].map(w=>`<p><span class="example-word">${w.split(' ')[0]}</span> <span class="zh-small">${w.slice(w.indexOf(' ')+1)}</span></p>`).join('')}<p class="zh-small">训练：遮住中文，尝试用“前缀 + ${x[0]} + 后缀”推测词义。</p></section>`).join('')}</div>`}
function renderTopics(q=''){const list=topicGroups.filter(g=>!q||g.name.includes(q)||g.items.flat().join(' ').toLowerCase().includes(q.toLowerCase()));return hero('作文话题词汇','先背“可以直接写进句子里的搭配”，再把主题名替换进去；避免只背孤立名词却不会造句。')+`<input id="specialSearch" class="study-filter" placeholder="搜索话题、短语或中文" value="${esc(q)}"><div class="study-actions"><a class="primary" href="./resources/essay-topic-vocabulary.pdf" target="_blank">打开完整16页原资料</a><button id="openTopicText">按页学习原资料</button></div><div class="root-grid">${list.map(g=>`<section class="study-card"><h4>${g.name}</h4>${g.items.map(i=>`<div class="topic-pair"><strong>${i[0]}</strong><span>${i[1]}</span></div>`).join('')}</section>`).join('')}</div>`}
function renderTranslation(){return hero('英译汉：每天 2 句精拆','推荐步骤：先断句并圈连接词，再找主干，处理修饰成分，最后按中文习惯重组。不要从第一个词机械翻到最后一个词。')+`<ol class="method-steps"><li>划分意群：介词短语、非谓语、从句边界先用斜线断开。</li><li>抓主干：先找谓语，再找主语和宾语；主干先译通。</li><li>识别关系：定语从句看修饰谁，状语从句看逻辑，名词性从句看充当什么成分。</li><li>中文重组：代词还原、被动转主动、抽象名词转动作，检查是否像自然汉语。</li></ol><div class="translation-grid">${translations.map((x,i)=>`<section class="study-card translation-item"><small>精译 ${i+1}</small><p class="translation-en">${x.en}</p><button class="revealTranslation">先自己翻，再看答案</button><div class="translation-answer"><h4>参考译文</h4><p>${x.zh}</p><div class="structure-line"><b>主干：</b>${x.main}</div><p><b>结构：</b>${x.chunks}</p><p><b>翻译提醒：</b>${x.tip}</p></div></section>`).join('')}</div>`}
function splitPages(t){return t.split(/\r?\n=== PAGE \d+(?: ERROR.*?)? ===\r?\n/).slice(1)}
async function loadPages(kind){const url=kind==='medical'?'./resources/medical353.txt':'./resources/essay-topics.txt';const pages=splitPages(await fetch(url).then(r=>r.text()));if(kind==='medical')medicalPages=pages;else topicPages=pages;return pages}
function pageReader(title,pages,kind){const max=pages.length;pageIndex=Math.max(0,Math.min(pageIndex,max-1));return `<div class="special-hero"><h3>${title}</h3><p>可按页阅读、搜索当前页；原资料内容保持原有顺序。</p></div><input id="pageSearch" class="study-filter" placeholder="在当前页查找关键词"><div class="page-nav"><button id="prevPage" ${pageIndex===0?'disabled':''}>上一页</button><b>第 ${pageIndex+1} / ${max} 页</b><button id="nextPage" ${pageIndex===max-1?'disabled':''}>下一页</button></div><pre id="sourceReader" class="source-reader">${esc(pages[pageIndex])}</pre><div class="study-actions"><button id="backTo${kind}">返回专题卡</button></div>`}
function renderMedical(){return hero('353 卫生综合独立专区','内容与英语学习完全分开。沿用材料中的零基础三轮法：首轮只认懂，第二轮掌握公式与方法，第三轮闭卷输出。')+`<section class="study-card"><h4>第一轮每天的最小闭环</h4><p>章首目标 5 分钟 → 基础讲解 20–30 分钟 → 合书复述 3 句话 → 基础题 2 道。看懂六成即可前进。</p></section><section class="study-card"><h4>三科入口</h4><p><b>流行病学：</b>谁得病、何时得、在哪里得，再比较人群并寻找原因。</p><p><b>卫生统计学：</b>把数据压缩成能理解的数字，再判断差异是真差异还是抽样波动。</p><p><b>社会医学：</b>从收入、教育、职业、地区和服务条件解释健康差异。</p></section><section class="study-card"><h4>完整教材学习</h4><p>共 470 页，包含 36 章、分层训练、公式、综合自测和答案。网页支持按页阅读，原 PDF 可单独打开核对图表和公式。</p><div class="study-actions"><button class="primary" id="openMedicalText">进入按页学习</button><a href="./resources/medical353.pdf" target="_blank">打开完整 PDF</a></div></section>`}
function bind(){document.querySelectorAll('[data-special]').forEach(b=>b.onclick=()=>{special=b.dataset.special;pageIndex=0;render()});const search=document.querySelector('#specialSearch');if(search)search.oninput=()=>{document.querySelector('#specialPanel').innerHTML=special==='roots'?renderRoots(search.value):renderTopics(search.value);bind()};document.querySelectorAll('.revealTranslation').forEach(b=>b.onclick=()=>{b.nextElementSibling.classList.toggle('show');b.textContent=b.nextElementSibling.classList.contains('show')?'收起答案':'先自己翻，再看答案'});const med=document.querySelector('#openMedicalText');if(med)med.onclick=async()=>{med.disabled=true;med.textContent='正在载入…';const p=medicalPages||await loadPages('medical');document.querySelector('#specialPanel').innerHTML=pageReader('卫生综合完整内容',p,'Medical');bind()};const top=document.querySelector('#openTopicText');if(top)top.onclick=async()=>{const p=topicPages||await loadPages('topic');document.querySelector('#specialPanel').innerHTML=pageReader('作文话题词汇原资料',p,'Topics');bind()};const prev=document.querySelector('#prevPage'),next=document.querySelector('#nextPage');if(prev)prev.onclick=()=>{pageIndex--;const p=medicalPages||topicPages;document.querySelector('#specialPanel').innerHTML=pageReader(medicalPages?'卫生综合完整内容':'作文话题词汇原资料',p,medicalPages?'Medical':'Topics');bind()};if(next)next.onclick=()=>{pageIndex++;const p=medicalPages||topicPages;document.querySelector('#specialPanel').innerHTML=pageReader(medicalPages?'卫生综合完整内容':'作文话题词汇原资料',p,medicalPages?'Medical':'Topics');bind()};const ps=document.querySelector('#pageSearch');if(ps)ps.oninput=()=>{const pre=document.querySelector('#sourceReader'),raw=(medicalPages||topicPages)[pageIndex],q=ps.value.trim();pre.innerHTML=q?esc(raw).replace(new RegExp(esc(q).replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'gi'),m=>`<mark>${m}</mark>`):esc(raw)};const bm=document.querySelector('#backToMedical');if(bm)bm.onclick=()=>{medicalPages=null;render()};const bt=document.querySelector('#backToTopics');if(bt)bt.onclick=()=>{topicPages=null;render()}}
function render(){document.querySelectorAll('[data-special]').forEach(b=>b.classList.toggle('on',b.dataset.special===special));const p=document.querySelector('#specialPanel');if(!p)return;p.innerHTML=special==='roots'?renderRoots():special==='topics'?renderTopics():special==='translation'?renderTranslation():renderMedical();bind()}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('#nav [data-page]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.page==='specialStudy')render()}));render()});
})();
