(()=>{
const collocations=[
['acquire knowledge/skills','acquire a habit','newly acquired'],['adapt to','adapt oneself to','adapt A for B'],['advocate doing sth.','advocate reform/change','an advocate of'],['an approach to doing','adopt an approach','as ... approaches'],['assess the impact/risk','assess whether','an assessment of'],['be available to','make sth. available','readily available'],['benefit from','be of benefit to','for the benefit of'],['pose/face a challenge','meet the challenge','challenge an assumption'],['as a consequence','a consequence of','have consequences for'],['contribute to','contribute A to B','make a contribution to'],['be crucial to/for','play a crucial role','at a crucial stage'],['decline to do','a decline in','on the decline'],['demonstrate that','demonstrate ability','clearly demonstrate'],['derive from','derive benefit from','be derived from'],['establish a relationship','establish that','be well established'],['it is evident that','become evident','self-evident'],['a key feature','a distinctive feature','feature in'],['maintain balance/order','maintain that','maintain contact with'],['modify a plan','modify behavior','a modified version'],['perceive A as B','be widely perceived','perceive a difference'],['potential for','realize one\'s potential','a potential risk'],['a significant difference','play a significant role','statistically significant'],['be reluctant to do','show reluctance','a reluctant agreement'],['sustain growth/interest','sustainable development','sustain damage'],['undergo change/treatment','undergo a transformation','undergo testing'],['illustrate a point','illustrate how/that','be illustrated by'],['indicate that','indicate a need','clearly indicate'],['interpret A as B','interpret the results','open to interpretation'],['justify doing','justify a decision','be justified in doing'],['reveal that','reveal information','reveal the nature of']];

const collocationZh=[['获得知识/技能','养成习惯','新近获得的'],['适应……','使自己适应……','为B改编A'],['提倡做某事','倡导改革/改变','……的拥护者'],['做某事的方法','采用一种方法','随着……临近'],['评估影响/风险','评估是否……','对……的评估'],['可供……使用','使某物可获得','随时可得的'],['从……受益','对……有益','为了……的利益'],['提出/面对挑战','迎接挑战','质疑某种假设'],['因此','……的后果','对……产生影响'],['促成；导致','向B捐献A','对……作出贡献'],['对……至关重要','发挥关键作用','在关键阶段'],['拒绝做某事','……的下降','正在衰退'],['表明……','展示能力','清楚地表明'],['源于……','从……获得益处','由……产生'],['建立关系','证实……','根深蒂固的'],['显而易见的是……','逐渐显现','不证自明的'],['关键特征','显著特征','在……中占重要位置'],['维持平衡/秩序','坚持认为……','与……保持联系'],['修改计划','改变行为','修改后的版本'],['把A视为B','被普遍认为','察觉差异'],['……的潜力/可能性','发挥潜能','潜在风险'],['显著差异','发挥重要作用','具有统计显著性'],['不愿做某事','表现出不情愿','勉强同意'],['维持增长/兴趣','可持续发展','遭受损害'],['经历变化/治疗','经历转变','接受测试'],['说明一个观点','说明如何/表明……','由……说明'],['表明……','表明有需要','清楚地表明'],['把A理解为B','解释结果','有多种解释'],['证明做某事合理','为决定辩护','有正当理由做某事'],['揭示……','披露信息','揭示……的性质']];
const collocationHeadwords=['acquire','adapt','advocate','approach','assess','available','benefit','challenge','consequence','contribute','crucial','decline','demonstrate','derive','establish','evident','feature','maintain','modify','perceive','potential','significant','reluctant','sustain','undergo','illustrate','indicate','interpret','justify','reveal'];

const sentenceGuides=[
['让步 → 转折 → 核心判断','主干：its real value lies in the way；Although 引出“降低成本”这一让步背景。','that it changes... 是定语从句，修饰 the way；rather than 把“新行为”与“更便宜的旧行为”对照。','不要把 although 从句翻成主结论；lies in 不是“躺在”，而是“在于”。','仿写：Although A may..., its real value lies in the way that it changes B.'],
['条件 → 结果 → 影响对象','主干：students can evaluate claims；Only when... 位于句首，引起部分倒装。','they have learned... 是时间/条件从句；that appear... 修饰 claims。','Only when 置于句首后，主句用 can students，而不是 students can。','仿写：Only when we understand A can we evaluate B.'],
['否定错误标准 → 提出正确标准','主干：A sound policy should be judged...；not by...but by...给出两个评判标准。','whether it works... 是 by 后的宾语从句；under real conditions 是条件状语。','whether 不译成“是否……吗”，整体译为“能否”。','仿写：A sound plan should be judged not by A, but by whether B.'],
['研究发现 → 因果解释','主干：People are more likely to remember...；who feel... 修饰 people。','because 引出原因；relate A to B 是固定结构。','more likely to 译为“更有可能”，不是“更喜欢”。','仿写：People are more likely to do A because they can relate it to B.'],
['表面事实 → 深层推论','主干：The finding suggests...；finding 前的 What 引导主语从句。','that 引导 suggest 的宾语从句；often hides... 是表语从句内部谓语。','What looks like... 整体作主语，不要逐词硬译。','仿写：What looks like A often hides B.'],
['时间推进 → 原因解释','主干：The debate has become less about A and more about B。','As evidence has accumulated 是时间/原因背景；how... 是介词 about 的宾语。','less about...and more about... 译为“与其说……不如说……”。','仿写：The debate is less about whether A and more about how B.'],
['否定表象 → 指出本质','主干：The difficulty comes from...；not from...but from...构成对照。','deciding which information deserves... 是介词 from 后的动名词短语；which 引导嵌入式疑问。','which information 不是定语从句，而是“哪些信息”的宾语从句。','仿写：The difficulty comes not from A, but from deciding B.'],
['让步承认 → 风险提醒','主干：the same convenience can reduce...；While 引出承认部分。','that saves time 修饰 convenience；if it discourages... 是条件从句。','the same convenience 指代前面的便利，翻译时要补足逻辑。','仿写：While A can..., the same A may...if B.'],
['研究者提醒 → 执行条件','主干：Researchers warn that reforms will fail...。','however carefully designed 是省略结构，相当于 however carefully they are designed；unless 引出必要条件。','unless = if...not，译为“除非/如果不”。','仿写：A will fail, however carefully designed, unless B.'],
['主语从句 → 系表结论','主干：What matters is...；not A but B 对比真正重要的因素。','whether the change is dramatic 与 whether it can be sustained 是两个表语成分。','sustained 此处是“持续下去”，不是“支撑物体”。','仿写：What matters is not whether A, but whether B.']];

const blueprints=[
{rows:[['描图与点题','The drawing shows <span class="slot">[人物/场景]</span>. It reminds us that <span class="slot">[中心品质]</span> matters in public life.'],['让步与危害','Admittedly, <span class="slot">[反方或现实困难]</span>. Yet <span class="slot">[不良行为]</span> may undermine <span class="slot">[公共利益]</span>.'],['建议与升华','For this reason, <span class="slot">[个人]</span> and <span class="slot">[机构]</span> should <span class="slot">[措施]</span>. Only when <span class="slot">[条件]</span> can <span class="slot">[结果]</span>.']],slots:[['中心品质','respect for rules / civic responsibility'],['公共利益','trust / safety / social order'],['措施','set clear rules / act responsibly']]},
{rows:[['描图','The picture portrays <span class="slot">[人物]</span> who keeps <span class="slot">[行动]</span> despite <span class="slot">[困难]</span>.'],['解释寓意','Its message is clear: <span class="slot">[品质]</span> turns repeated effort into visible progress.'],['双层建议','On the individual level, we should <span class="slot">[行动1]</span>. On the social level, schools and employers can <span class="slot">[行动2]</span>.']],slots:[['品质','perseverance / patience / self-discipline'],['行动1','set realistic goals'],['行动2','reward steady improvement']]},
{rows:[['称呼与目的','Dear <span class="slot">[称呼]</span>, I am writing to offer several suggestions concerning <span class="slot">[主题]</span>.'],['建议一','First, it would be helpful to <span class="slot">[措施1]</span>, because <span class="slot">[理由1]</span>.'],['建议二','In addition, I suggest that <span class="slot">[措施2]</span>, which would <span class="slot">[效果]</span>.'],['收尾','Thank you for considering these suggestions. I look forward to <span class="slot">[期待]</span>.']],slots:[['主题','the reading program / campus service'],['措施','extend opening hours / provide guidance'],['期待','your reply / future improvement']]},
{rows:[['身份或背景','As <span class="slot">[身份]</span>, I sincerely appreciate <span class="slot">[对方的安排/帮助]</span>.'],['写信目的','I am writing to apologize for being unable to <span class="slot">[原约定]</span>.'],['解释原因','Unfortunately, <span class="slot">[客观原因]</span>, which makes it impossible for me to <span class="slot">[行动]</span>.'],['提出补救','If possible, I hope <span class="slot">[补救方案]</span>.'],['再次致歉','Please accept my sincere apology for <span class="slot">[造成的不便]</span>.'],['期待回复','I would appreciate it if you could <span class="slot">[期望对方回应]</span>.']],slots:[['身份','a participant / your student'],['客观原因','I have an urgent work assignment'],['补救方案','the meeting can be rearranged'],['期望回应','let me know whether this is possible']]}];

function bestVoice(){const vs=speechSynthesis.getVoices();return vs.find(v=>/enhanced|premium|siri/i.test(v.name)&&/^en/i.test(v.lang))||vs.find(v=>/Samantha|Ava|Serena|Karen|Daniel|Moira|Google UK English Female|Microsoft Sonia/i.test(v.name))||vs.find(v=>/^en-GB/i.test(v.lang))||vs.find(v=>/^en/i.test(v.lang));}
let mode=localStorage.getItem('wifeSpeechMode')||'normal';
let playbackId=0, playbackTimer=null, activeUtterance=null, cachedVoice;
function refreshVoice(){cachedVoice=bestVoice()}
refreshVoice();
speechSynthesis.addEventListener('voiceschanged',refreshVoice);
function playbackStatus(message){
  let el=document.getElementById('playback-status');
  if(!el){el=document.createElement('div');el.id='playback-status';el.setAttribute('role','status');el.style.cssText='position:fixed;bottom:18px;left:50%;transform:translateX(-50%);z-index:10000;background:#172844;color:white;padding:9px 16px;border-radius:16px;font-size:13px;pointer-events:none';document.body.appendChild(el)}
  el.textContent=message;el.hidden=!message;
}
function clauses(t){return (t.match(/[^.!?]+[.!?]?/g)||[t]).map(x=>x.trim()).filter(Boolean)}
function expressive(text,repeat=1,forced){
  const id=++playbackId;
  clearTimeout(playbackTimer);
  if(activeUtterance){activeUtterance.onend=null;activeUtterance.onerror=null;activeUtterance.onstart=null}
  if(speechSynthesis.speaking||speechSynthesis.pending||activeUtterance)speechSynthesis.cancel();
  activeUtterance=null;
  if(speechSynthesis.paused)speechSynthesis.resume();
  const parts=clauses(String(text||'')),selected=forced||mode;
  if(!parts.length){playbackStatus('');return}
  const queue=Array.from({length:repeat},()=>parts).flat();let index=0;
  playbackStatus('正在启动朗读…');
  function next(){
    if(id!==playbackId)return;
    if(index>=queue.length){activeUtterance=null;playbackStatus('');return}
    const u=new SpeechSynthesisUtterance(queue[index++]);activeUtterance=u;
    const voice=cachedVoice||bestVoice();if(voice)u.voice=voice;
    u.lang=voice?.lang||'en-US';u.rate=selected==='slow'?.54:selected==='natural'?.82:.68;u.pitch=1;u.volume=1;
    u.onstart=()=>{if(id===playbackId)playbackStatus('正在朗读…')};
    u.onend=()=>{if(id!==playbackId)return;activeUtterance=null;if(index===queue.length){playbackStatus('');return}playbackTimer=setTimeout(next,selected==='slow'?360:220)};
    u.onerror=()=>{if(id!==playbackId)return;activeUtterance=null;playbackStatus('朗读未启动，请再点一次');playbackTimer=setTimeout(()=>{if(id===playbackId)playbackStatus('')},3000)};
    speechSynthesis.speak(u);
  }
  next(); // First utterance is submitted synchronously in the user's click event.
}
window.speak=expressive;

function insertSpeechPanels(){document.querySelectorAll('.screen').forEach(screen=>{if(screen.querySelector('.speech-panel'))return;const p=document.createElement('div');p.className='speech-panel';p.innerHTML='<div class="speech-title">朗读速度</div><div class="speech-buttons"><button class="speech-mode" data-mode="natural">自然朗读</button><button class="speech-mode" data-mode="normal">四六级慢速</button><button class="speech-mode" data-mode="slow">逐句精听</button></div><div class="speech-note">新版按完整句子朗读，让苹果语音自己处理句内重音，不再在每个逗号处生硬断开。</div><details class="ios-voice-help"><summary>苹果声音仍机械？点这里设置</summary>在 iPhone 打开“设置 → 辅助功能 → 朗读内容 → 声音 → 英语”，下载 Samantha、Ava 等增强版语音；下载后完全关闭 Safari 再重新打开网页。网页只能调用手机已有的声音，不能凭空变成真人录音。</details>';screen.insertBefore(p,screen.children[1]||null)});syncMode();document.querySelectorAll('.speech-mode').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;localStorage.setItem('wifeSpeechMode',mode);syncMode()})}
function syncMode(){document.querySelectorAll('.speech-mode').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode))}

const oldWord=window.word;window.word=function(){oldWord();let box=document.querySelector('.collocations');if(!box){box=document.createElement('section');box.className='collocations';document.getElementById('listenExample').after(box)}const headword=words[st.i%words.length].a.toLowerCase(),n=collocationHeadwords.indexOf(headword),list=n>=0?collocations[n]:[],zh=n>=0?collocationZh[n]:[];box.innerHTML=list.length?'<h4>历年真题常见搭配</h4>'+list.map((x,i)=>'<span class="collocation-item"><b>'+x+'</b><small>'+zh[i]+'</small></span>').join('')+'<div class="speech-note">先记“词 + 搭配”，再回到例句判断词义；这里是独立整理的常见用法，不代表官方频次排名。</div>':'<div class="speech-note">该词的搭配、音标与例句正在按词频分批校验；本版先保证 5529 个大纲词头和简明释义完整。</div>';};

const accurateGuides=[
['让步背景 → 转折评价','主干：its real value lies in the way；核心意思是“真正价值在于这种方式”。','Although...costs 是让步状语；it encourages... 是省略 that 的定语从句，修饰 the way；how limited resources are allocated 是 reconsider 的宾语从句。','how 从句不直接修饰 the way；allocated 是被动语态，应译为“资源如何被分配”。','Although A was introduced to do B, its real value lies in the way it encourages C to do D.'],
['强调原因 → 两项对照','主干：What makes the evidence persuasive is not A, but B。What 从句整体作主语。','with which the same pattern appears... 是“介词 + which”定语从句，修饰 consistency；across different groups 是范围状语。','not A alone, but B 是“不只在于 A，更在于 B”，不要漏掉 alone 的限定意味。','What makes A convincing is not B alone, but the consistency with which C happens.'],
['限定研究者 → 指出遗漏','主干：Researchers may overlook changes。','who focus... 修饰 Researchers；that are... 修饰 changes；affected 是过去分词，修饰 people。','no less important = 同样重要，并非“不太重要”；less visible 与 no less important 形成让步式对照。','People who focus only on A may overlook B that is less visible but no less important.'],
['提出假设 → 指出忽视','主干：The assumption ignores the fact。','第一个 that 是 assumption 的同位语从句，说明“什么假设”；第二个 that 是 fact 的同位语从句；not only what... but also who... 并列两个宾语从句。','what people say 与 who gets heard 都是 alter 的宾语；get heard 是 get + 过去分词，表示“被听见”。','The assumption that A ignores the fact that B affects not only C but also D.'],
['时间界限 → 主句推测','主干：the conditions may already have changed。','By the time...statistics 是时间状语从句；that produced it 修饰 conditions，it 指 social habit；may have changed 表示对已经发生之事的推测。','By the time 常与完成意义搭配；不要把 may have done 误译成“可能会”。','By the time A becomes visible, the conditions that produced it may already have changed.'],
['否定提问方式 → 提出考察对象','主干：we should examine the circumstances and those。those 代替 circumstances，避免重复。','Rather than asking... 是介词短语作状语；under which it works well 修饰 circumstances；in which it does not 修饰 those。','universally better 不是“宇宙中更好”，而是“普遍更好”；does not 后省略 work well。','Rather than asking whether A, we should examine the circumstances under which B.'],
['越……越…… → 得出倾向','主干：the less likely they are to confuse A with B。','The more carefully...information 是前半比较分句；两个 that 分别修饰两次 information；merely attracts attention 与 is useful 对照。','The more..., the less... 前后都不是独立疑问句；confuse A with B 是“把 A 与 B 混淆”。','The more carefully people distinguish A from B, the less likely they are to confuse C with D.'],
['局部视角 → 外部成本 → 原因说明','主干：A decision can create costs elsewhere。','that appears efficient... 修饰 decision；which 指代前面整件事；why cooperation... 是 is 后的表语从句。','which 不是只指 costs，而是指“局部高效却在别处产生成本”这一事实。','A decision that appears A from one perspective can create B elsewhere, which is why C.'],
['目的条件 → 必要要求','主干：it must offer not merely A but B。it 指 a proposal。','For a proposal to gain... 是目的/条件意味的不定式结构；how that improvement will be achieved 是介词 of 后 account 的内容。','account 在这里是“说明、解释”，不是“账户”；not merely...but... 是递进。','For A to gain support, it must offer not merely B but a credible account of how C.'],
['是否接受 → 两方面原因','主干：Whether people accept a change depends partly on A and partly on B。','Whether... 是主语从句；to which... 修饰 extent；they believe... 是 extent 内部内容，their concerns have been considered 是 believe 的宾语从句。','the extent to which 是固定学术结构，译为“……的程度”；considered 是被动完成。','Whether A happens depends partly on B and partly on the extent to which C.']];
S[0][2]='Although 引导让步状语；it encourages... 是修饰 the way 的定语从句；how limited resources are allocated 是 reconsider 的宾语从句。';
const oldSentence=window.sentence;window.sentence=function(){oldSentence();const root=document.getElementById('sentenceZh').parentElement;let trans=root.querySelector('.translation-focus');if(!trans){trans=document.createElement('div');trans.className='translation-focus';root.insertBefore(trans,document.getElementById('sentenceZh'));document.getElementById('sentenceZh').style.display='none'}trans.innerHTML='<strong>完整译文</strong>'+S[st.s%S.length][3];let deep=root.querySelector('.deep-analysis');if(!deep){deep=document.createElement('section');deep.className='deep-analysis';root.appendChild(deep)}const g=accurateGuides[st.s%accurateGuides.length];deep.innerHTML='<h4>老师式五步拆句</h4>'+['逻辑路线','先抓主干','再拆修饰','易错警报','迁移仿写'].map((h,i)=>'<div class="analysis-step"><b>'+h+'</b>'+g[i]+'</div>');};

if(E.length===3){E.push(['应用文：道歉信','Apology for Missing an Appointment','Dear Professor Wang,\n\nAs a participant in the research meeting, I sincerely appreciate your invitation. I am writing to apologize for being unable to attend our appointment tomorrow.\n\nUnfortunately, I have been assigned an urgent task at work, which requires me to remain on site. If possible, I hope the meeting can be rearranged for Friday afternoon.\n\nPlease accept my sincere apology for the inconvenience. I would appreciate it if you could let me know whether the new time is suitable.\n\nYours sincerely,\nLi Ming','身份/背景 → 写信目的 → 客观原因 → 补救方案 → 再次致歉 → 期待回复']);essayTranslations.push('尊敬的王教授：\n\n作为研究会议的参与者，我衷心感谢您的邀请。我写信是为了就无法参加明天的约定向您道歉。\n\n遗憾的是，我临时接到一项紧急工作任务，需要留在现场。如果可以，我希望把会议改到周五下午。\n\n对于由此带来的不便，请接受我诚挚的歉意。如您能告知新的时间是否合适，我将不胜感激。\n\n您真诚的，\n李明')}
const oldEssay=window.essay;window.essay=function(){oldEssay();let box=document.querySelector('.essay-blueprint');if(!box){box=document.createElement('section');box.className='essay-blueprint';document.getElementById('essayFrame').parentElement.appendChild(box)}const b=blueprints[st.e%E.length]||blueprints[0];box.innerHTML='<h4>可套用框架（功能句 + 替换槽）</h4><div class="essay-annotation">'+b.rows.map(r=>'<p><span class="function-label">'+r[0]+'</span><br><span class="template-en">'+r[1]+'</span></p>').join('')+'</div><table class="replacement-table"><tr><th>替换位置</th><th>可换表达</th></tr>'+b.slots.map(r=>'<tr><td>'+r[0]+'</td><td>'+r[1]+'</td></tr>').join('')+'</table><div class="speech-note">框架负责结构，不要整篇机械套用；考场上至少替换主题词、原因和措施。</div>';};

function bindSlow(){[['listenWord',()=>words[st.i%words.length].a,3],['listenExample',()=>words[st.i%words.length].d,1],['listenSentence',()=>S[st.s%S.length][0],1],['listenEssay',()=>E[st.e%E.length][2],1]].forEach(([id,get,rep])=>{const btn=document.getElementById(id);if(!btn||btn.parentElement.querySelector('[data-slow-for="'+id+'"]'))return;const slow=document.createElement('button');slow.className='slow-read';slow.dataset.slowFor=id;slow.textContent=id==='listenWord'?'慢读单词 ×3':'慢速精听';slow.onclick=()=>expressive(get(),rep,'slow');btn.after(slow)})}
insertSpeechPanels();bindSlow();document.querySelectorAll('.audio-hint').forEach(x=>x.textContent='新版按完整句自然连读，只在句号处停顿；再次点朗读可从头播放。');word();sentence();essay();
document.getElementById('nextSentence').addEventListener('click',()=>setTimeout(sentence));document.getElementById('nextEssay').addEventListener('click',()=>setTimeout(essay));
})();
